### ISSUE TITLE
warn: Loading of fingerprint-brunch failed due to Cannot find module 'crypto-js'

### ISSUE THREAD

**Issue by AdaptCharm** [dlepaux/fingerprint-brunch#19]
Error msg:
00:21:28 - warn: Loading of fingerprint-brunch failed due to Cannot find module 'crypto-js'

Please fix this bug asap. Would be much appreciated.

**Comment by dlepaux** [comment]
@AdaptCharm,
Which version do you use ?
Can you remove your `node_modules` repo and make `npm install`. You still have the error ?

**Comment by dlepaux** [comment]
@AdaptCharm
