### ISSUE TITLE
'assetsToFingerprint' doesn't respect 'environments' when specified as an array

### ISSUE THREAD

**Issue by dmtaub** [dlepaux/fingerprint-brunch#37]
steps to repro:
```git checkout git@github.com:dlepaux/fingerprint-brunch-example.git
cd fingerprint-brunch-example
npm install
```
remove lines:  'alwaysRun: true' and 'autoReplaceAndHash: true' or set to `false`
wrap assetsToFingerprint directive in brackets -- `assetsToFingerprint: ['/img/troll.png']`
```
NODE_ENV=dev brunch build
ls public/img/
```
shows troll-a8384a20.png -- hashed file, even though it ran in non-production environment 

Is this expected behavior? If so, please document that.

**Comment by dlepaux** [comment]
Hello @dmtaub,
No it's not the expected behavior ! I'm on it.

**Comment by dlepaux** [comment]
Hello @dmtaub ,

The assetsToFingerprint directive must contain an array.. The brunch config (in the example) is wrong (my bad sorry). I have just fixed that.

I have add a check on environment for assetsToFingerprint and folderToFingerprint.

I release the 2.0.6.
Thanks
