### ISSUE TITLE
assets rev not working when called from multiple source files

### ISSUE THREAD

**Issue by mlarcher** [dlepaux/fingerprint-brunch#7]
When generating multiple css files from brunch by declaring two scss files in the stylesheets joinTo that depend on the same png image, the second one's url doesn't get replaced. I believe this is because the asset has already been renamed when handling the first file. Could you maybe do something about it ?

**Comment by dlepaux** [comment]
Hello @mlarcher, if you have the time, a PR is very welcome. Thanks

**Comment by dlepaux** [comment]
@mlarcher I just do some test to reproduce your issue but it seem to work fine !
