### ISSUE TITLE
Fingerprinting for non-js/css assets

### ISSUE THREAD

**Issue by funk-yourself** [dlepaux/fingerprint-brunch#9]
It's quite unclear for me how to get manifest like this (from Readme):
```js
{
  "css/master.css": "css/master-364b42a1.css",
  "js/master.js": "js/master-cb60c02b.js",
  "img/troll.png": "img/troll-5f2d5cbe.png",
  "fonts/font.eot": "fonts/font-45d860a3.eot",
  "fonts/font.woff": "fonts/font-6ced13b9.woff",
  "fonts/font.ttf": "fonts/font-82c653e7.ttf",
  "fonts/font.svg": "fonts/font-52343d4f.svg"
}
```
I mean that it includes assets like *.png, *.svg, etc.
I put my picture_name.png into assets folder, and it gets copied properly to my public/assets directory during ```brunch build```, but it's neither fingerprinted, nor put into assets.json (only *.js files can be seen there).

**Comment by dlepaux** [comment]
Hello @funk-yourself,

First you need to enable this flag in your config (autoReplaceAndHash)[https://github.com/dlepaux/fingerprint-brunch#autoreplaceandhash].

This feature will fingerprint all assets files (.ttf, .svg, .png) linked in your CSS.

Next remove unecessaray path thanks to (srcBasePath)[https://github.com/dlepaux/fingerprint-brunch#srcbasepath], (destBasePath)[https://github.com/dlepaux/fingerprint-brunch#destbasepath].

**Comment by funk-yourself** [comment]
Thank you for reply! Ok, now I got this. Didn't understand that it only fingerprints these ones which are linked in CSS.

**Comment by dlepaux** [comment]
@funk-yourself If you are interested, I'm currently develop a feature to fingerprint (and map) some specific files by configuring a path or by specifying files into fingeprrint brunch-config.
If you have some specification it's the moment to tell me :)

**Comment by dlepaux** [comment]
@funk-yourself Feature is done ;)
